import random
rn1 = random.randint(1,100)
#print(random_number) this function shows you the answer generated by python
win = 0
#Turns =0
while win==0:
    guess =int(input("Enter a number between 1 and 100 "))
    #Turns +=1
    if rn1==guess:
        print("You won!")
        #print("Number of turns you have used: ",Turns)
        win == 1
        break
    else:
     if rn1>guess:
        print("Your Guess was low, Please enter a higher number")
     else:
        print("your guess was high, please enter a lower number")


    